---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'

rules:
  no-console: error
  import/extensions: 0
  import/prefer-default-export: 0
  array-callback-return: 0
  consistent-return: 0
  arrow-body-style: 0
  no-underscore-dangle: 0
  prefer-const: 0
  no-use-before-define: 0
